package org.interfaithsanctuary.donationapi.controller;

import org.interfaithsanctuary.donationapi.repository.AlertRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api/alert/") // This means URL's start with /demo (after Application path)
public class AlertController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AlertRepository alertRepository;

    @GetMapping(path="all")
    public @ResponseBody
    Iterable<Alert> getAllAlerts() {
        // This returns a JSON or XML with the users
        return alertRepository.findAll();
    }

    @GetMapping(path="{id}")
    public @ResponseBody Alert getAlertById(@PathVariable("id") long id)  {
        return alertRepository.findOne(id);
    }



}