package org.interfaithsanctuary.donationapi.controller;

import org.interfaithsanctuary.donationapi.model.Callout;
import org.interfaithsanctuary.donationapi.repository.CalloutRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api/callout/") // This means URL's start with /demo (after Application path)
public class CalloutController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CalloutRepository calloutRepository;

    @GetMapping(path="all")
    public @ResponseBody Iterable<Callout> getAllCallouts() {
        // This returns a JSON or XML with the users
        return calloutRepository.findAll();
    }

    @GetMapping(path="{id}")
    public @ResponseBody Callout getCalloutById(@PathVariable("id") long id)  {
        return calloutRepository.findOne(id);
    }



}