package org.interfaithsanctuary.donationapi.controller;

import org.interfaithsanctuary.donationapi.model.Gift;
import org.interfaithsanctuary.donationapi.repository.GiftRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api/gift/") // This means URL's start with /api (after Application path)
public class GiftController {

    @Autowired // This means to get the bean called giftRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GiftRepository giftRepository;

    @RequestMapping(value = "/all", method = RequestMethod.GET)
    public @ResponseBody Iterable<Gift> getAllGifts() {
        // This returns a JSON or XML with the callouts
        return giftRepository.findAll();
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public @ResponseBody Gift getGiftById(@PathVariable("id") long id)  {

        return giftRepository.findOne(id);
    }

}